services:
  app:
    build: .
    container_name: desafio_dev
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    container_name: desafio_dev_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  postgres_data:
