default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  database: desafio_dev_development

test:
  <<: *default
  database: desafio_dev_test

production:
  primary: &primary_production
    <<: *default
    database: desafio_dev_production
    username: desafio_dev
    password: <%= ENV["DESAFIO_DEV_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: desafio_dev_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: desafio_dev_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: desafio_dev_production_cable
    migrations_paths: db/cable_migrate
